--- /KernelSU-Next/kernel/Makefile	2025-04-28 20:42:04.052332688 +0800
+++ /KernelSU-Next/kernel/Makefile	2025-04-28 18:14:14.478917441 +0800
@@ -49,6 +49,14 @@
 ccflags-y += -DKSU_KERNEL_WRITE
 endif
 
+ifndef KSU_EXPECTED_SIZE
+KSU_EXPECTED_SIZE := 0x033b
+endif
+
+ifndef KSU_EXPECTED_HASH
+KSU_EXPECTED_HASH := c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
+endif
+
 ifndef KSU_NEXT_EXPECTED_SIZE
 KSU_NEXT_EXPECTED_SIZE := 0x3e6
 endif
@@ -57,6 +65,30 @@
 KSU_NEXT_EXPECTED_HASH := 79e590113c4c4c0c222978e413a5faa801666957b1212a328e46c00c69821bf7
 endif
 
+ifndef KSU_LEGACY_EXPECTED_SIZE
+KSU_LEGACY_EXPECTED_SIZE := 0x396
+endif
+
+ifndef KSU_LEGACY_EXPECTED_HASH
+KSU_LEGACY_EXPECTED_HASH := f415f4ed9435427e1fdf7f1fccd4dbc07b3d6b8751e4dbcec6f19671f427870b
+endif
+
+ifndef KSU_MAGIC_EXPECTED_SIZE
+KSU_MAGIC_EXPECTED_SIZE := 0x363
+endif
+
+ifndef KSU_MAGIC_EXPECTED_HASH
+KSU_MAGIC_EXPECTED_HASH := 4359c171f32543394cbc23ef908c4bb94cad7c8087002ba164c8230948c21549
+endif
+
+ifndef KSU_SUKI_EXPECTED_SIZE
+KSU_SUKI_EXPECTED_SIZE := 0x35c
+endif
+
+ifndef KSU_SUKI_EXPECTED_HASH
+KSU_SUKI_EXPECTED_HASH := 947ae944f3de4ed4c21a7e4f7953ecf351bfa2b36239da37a34111ad29993eef
+endif
+
 ifdef KSU_MANAGER_PACKAGE
 ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
 $(info -- KernelSU-Next Manager package name: $(KSU_MANAGER_PACKAGE))
@@ -63,10 +95,26 @@
 endif
 
-$(info -- KernelSU-Next Manager signature size: $(KSU_NEXT_EXPECTED_SIZE))
-$(info -- KernelSU-Next Manager signature hash: $(KSU_NEXT_EXPECTED_HASH))
+$(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
+$(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))
+$(info -- KernelSU Next Manager signature size: $(KSU_NEXT_EXPECTED_SIZE))
+$(info -- KernelSU Next Manager signature hash: $(KSU_NEXT_EXPECTED_HASH))
+$(info -- KernelSU Legacy Manager signature size: $(KSU_LEGACY_EXPECTED_SIZE))
+$(info -- KernelSU Legacy Manager signature hash: $(KSU_LEGACY_EXPECTED_HASH))
+$(info -- KernelSU Magic Manager signature size: $(KSU_MAGIC_EXPECTED_SIZE))
+$(info -- KernelSU Magic Manager signature hash: $(KSU_MAGIC_EXPECTED_HASH))
+$(info -- KernelSU Suki Manager signature size: $(KSU_SUKI_EXPECTED_SIZE))
+$(info -- KernelSU Suki Manager signature hash: $(KSU_SUKI_EXPECTED_HASH))
 
+ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
+ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"
 ccflags-y += -DEXPECTED_NEXT_SIZE=$(KSU_NEXT_EXPECTED_SIZE)
 ccflags-y += -DEXPECTED_NEXT_HASH=\"$(KSU_NEXT_EXPECTED_HASH)\"
+ccflags-y += -DEXPECTED_LEGACY_SIZE=$(KSU_LEGACY_EXPECTED_SIZE)
+ccflags-y += -DEXPECTED_LEGACY_HASH=\"$(KSU_LEGACY_EXPECTED_HASH)\"
+ccflags-y += -DEXPECTED_MAGIC_SIZE=$(KSU_MAGIC_EXPECTED_SIZE)
+ccflags-y += -DEXPECTED_MAGIC_HASH=\"$(KSU_MAGIC_EXPECTED_HASH)\"
+ccflags-y += -DEXPECTED_SUKI_SIZE=$(KSU_SUKI_EXPECTED_SIZE)
+ccflags-y += -DEXPECTED_SUKI_HASH=\"$(KSU_SUKI_EXPECTED_HASH)\"
 
 ccflags-y += -DKSU_COMPAT_GET_CRED_RCU
 
